import React, { useState, useRef } from 'react';
import { GeneratedSection, ExerciseType } from '../types';
import { Volume2, CheckCircle2, XCircle, BookOpen, Brain, Mic, Image as ImageIcon } from 'lucide-react';
import { generateAudio } from '../services/geminiService';

interface ExerciseCardProps {
  section: GeneratedSection;
  sectionIndex: number;
  showAnswersGlobal: boolean;
  userAnswers: Record<string, string>;
  onAnswerSelect: (sectionIdx: number, questionIdx: number, option: string) => void;
  isSubmitted: boolean;
}

const ExerciseCard: React.FC<ExerciseCardProps> = ({ 
  section, 
  sectionIndex,
  showAnswersGlobal,
  userAnswers,
  onAnswerSelect,
  isSubmitted
}) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isLoadingAudio, setIsLoadingAudio] = useState(false);
  const audioContextRef = useRef<AudioContext | null>(null);
  
  // Icons mapping
  const getIcon = () => {
    switch(section.type) {
      case ExerciseType.GRAMMAR: return <Brain className="w-5 h-5" />;
      case ExerciseType.READING: return <BookOpen className="w-5 h-5" />;
      case ExerciseType.LISTENING: return <Mic className="w-5 h-5" />;
      case ExerciseType.IMAGE_MATCHING: return <ImageIcon className="w-5 h-5" />;
      default: return <BookOpen className="w-5 h-5" />;
    }
  };

  const handlePlayAudio = async () => {
    if (!section.contextText) return;
    if (isPlaying) return;

    setIsLoadingAudio(true);
    try {
      const audioBuffer = await generateAudio(section.contextText);
      
      if (!audioContextRef.current) {
        audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
      }
      
      const ctx = audioContextRef.current;
      const source = ctx.createBufferSource();
      source.buffer = audioBuffer;
      source.connect(ctx.destination);
      
      source.onended = () => setIsPlaying(false);
      
      source.start(0);
      setIsPlaying(true);
    } catch (error) {
      alert("Could not generate audio at this time.");
    } finally {
      setIsLoadingAudio(false);
    }
  };

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden mb-8">
      {/* Header */}
      <div className="bg-slate-50 px-6 py-4 border-b border-slate-100 flex items-center justify-between">
        <div className="flex items-center gap-2 text-indigo-700 font-semibold">
          {getIcon()}
          <span>{section.type}</span>
        </div>
        <span className="text-xs font-mono text-slate-400 bg-slate-200 px-2 py-1 rounded">
          {section.id}
        </span>
      </div>

      <div className="p-6">
        <h3 className="text-xl font-bold text-slate-800 mb-2">{section.title}</h3>
        <p className="text-slate-600 mb-6 italic">{section.instruction}</p>

        {/* Context / Reading / Listening Trigger */}
        {section.contextText && (
          <div className="mb-8 p-5 bg-slate-50 rounded-xl border border-slate-100">
            {section.type === ExerciseType.LISTENING ? (
              <div className="flex flex-col items-center justify-center py-4">
                <button
                  onClick={handlePlayAudio}
                  disabled={isLoadingAudio || isPlaying}
                  className={`flex items-center gap-2 px-6 py-3 rounded-full font-semibold transition-all shadow-sm ${
                    isPlaying 
                    ? 'bg-green-100 text-green-700 border border-green-200' 
                    : 'bg-indigo-600 text-white hover:bg-indigo-700 hover:shadow-md'
                  }`}
                >
                  {isLoadingAudio ? (
                    <span className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></span>
                  ) : (
                    <Volume2 className={`w-5 h-5 ${isPlaying ? 'animate-pulse' : ''}`} />
                  )}
                  {isPlaying ? 'Playing Audio...' : 'Play Listening Track'}
                </button>
                <div className="mt-4 text-xs text-slate-400">
                    Audio generated by Gemini 2.5 TTS
                </div>
                {/* Optional: Show script toggle for checking */}
                {showAnswersGlobal && (
                    <div className="mt-4 w-full text-sm text-slate-600 border-t border-slate-200 pt-3">
                        <span className="font-bold block mb-1">Transcript:</span>
                        {section.contextText}
                    </div>
                )}
              </div>
            ) : (
              <div className="prose prose-slate max-w-none">
                <p className="text-slate-800 leading-relaxed whitespace-pre-line">{section.contextText}</p>
              </div>
            )}
          </div>
        )}

        {/* Questions */}
        <div className="space-y-6">
          {section.questions.map((q, idx) => (
            <QuestionItem 
              key={idx} 
              question={q} 
              index={idx} 
              sectionIndex={sectionIndex}
              userSelected={userAnswers[`${sectionIndex}-${idx}`]}
              onSelect={(opt) => onAnswerSelect(sectionIndex, idx, opt)}
              showAnswer={showAnswersGlobal} 
              isSubmitted={isSubmitted}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

interface QuestionItemProps {
  question: any;
  index: number;
  sectionIndex: number;
  userSelected: string | undefined;
  onSelect: (option: string) => void;
  showAnswer: boolean;
  isSubmitted: boolean;
}

const QuestionItem: React.FC<QuestionItemProps> = ({ 
  question, 
  index, 
  userSelected, 
  onSelect, 
  showAnswer,
  isSubmitted 
}) => {
  const isCorrect = userSelected === question.correctAnswer;

  return (
    <div className="border-b border-slate-100 pb-6 last:border-0 last:pb-0">
      <div className="flex gap-3">
        <span className={`flex-shrink-0 w-8 h-8 rounded-full text-sm font-bold flex items-center justify-center mt-0.5 transition-colors ${
           isSubmitted 
             ? (isCorrect ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700')
             : 'bg-slate-100 text-slate-600'
        }`}>
          {isSubmitted ? (isCorrect ? <CheckCircle2 className="w-5 h-5" /> : <XCircle className="w-5 h-5" />) : index + 1}
        </span>
        <div className="flex-grow">
          {/* Question Text */}
          <p className="font-medium text-slate-800 mb-3 text-lg leading-snug">{question.questionText}</p>

          {/* Generated Image (For Image Matching) */}
          {question.questionImage && (
            <div className="mb-6 max-w-sm">
                <div className="rounded-xl overflow-hidden border border-slate-200 shadow-sm relative group bg-slate-50">
                    <img 
                      src={question.questionImage} 
                      alt="Identify this" 
                      className="w-full h-auto object-cover max-h-64"
                    />
                     <div className="absolute bottom-2 right-2 bg-black/60 text-white text-xs px-2 py-1 rounded backdrop-blur-sm flex items-center gap-1">
                        <ImageIcon className="w-3 h-3" />
                        AI Generated
                    </div>
                </div>
            </div>
          )}
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {question.options && question.options.map((opt: string, i: number) => {
              const isSelected = userSelected === opt;
              const isTheCorrectAnswer = opt === question.correctAnswer;
              
              let buttonClass = "bg-white border-slate-200 hover:bg-slate-50";

              if (isSubmitted || showAnswer) {
                if (isTheCorrectAnswer) {
                  // Always highlight correct answer in green if submitted or showing answers
                  buttonClass = "bg-green-50 border-green-500 text-green-900 ring-1 ring-green-500";
                } else if (isSelected && !isTheCorrectAnswer) {
                  // Highlight wrong selection in red
                  buttonClass = "bg-red-50 border-red-500 text-red-900 ring-1 ring-red-500";
                } else {
                  // Dim others
                  buttonClass = "opacity-50 border-slate-100";
                }
              } else {
                // Interactive state
                if (isSelected) {
                  buttonClass = "bg-indigo-50 border-indigo-500 text-indigo-900 ring-1 ring-indigo-500";
                }
              }

              return (
                <button
                  key={i}
                  onClick={() => !isSubmitted && onSelect(opt)}
                  disabled={isSubmitted || showAnswer}
                  className={`text-left px-5 py-4 border rounded-xl text-base transition-all duration-200 ${buttonClass}`}
                >
                  <span className="font-semibold mr-3 opacity-60 uppercase">{String.fromCharCode(65 + i)}.</span>
                  {opt}
                </button>
              );
            })}
          </div>

          {/* Explanation / Result */}
          {(showAnswer || (isSubmitted && !isCorrect)) && (
            <div className={`mt-4 p-4 rounded-xl text-sm flex gap-3 ${isSubmitted && !isCorrect ? 'bg-red-50 text-red-900' : 'bg-blue-50 text-blue-800'}`}>
               <div className="mt-0.5 flex-shrink-0">
                 {isSubmitted && !isCorrect ? <XCircle className="w-5 h-5 text-red-600" /> : <CheckCircle2 className="w-5 h-5 text-blue-600" />}
               </div>
               <div>
                 <span className="font-bold block mb-1">
                    {isSubmitted && !isCorrect ? 'Incorrect. ' : ''}
                    Correct Answer: {question.correctAnswer}
                 </span>
                 {question.explanation}
               </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ExerciseCard;